// <auto-generated/>
#nullable enable
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace KeelMatrix.QueryWatch.Contracts
{
    /// <summary>
    /// System.Text.Json source-generation context for QueryWatch contracts.
    /// Use this in callers: JsonSerializer.Deserialize(stream, QueryWatchJsonContext.Default.Summary)
    /// </summary>
    [JsonSourceGenerationOptions(
        WriteIndented = false,
        PropertyNamingPolicy = JsonKnownNamingPolicy.Unspecified,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        GenerationMode = JsonSourceGenerationMode.Metadata)]
    [JsonSerializable(typeof(Summary))]
    [JsonSerializable(typeof(EventSample))]
    [JsonSerializable(typeof(Dictionary<string, string>))]
    [JsonSerializable(typeof(Dictionary<string, JsonElement>))]
    public partial class QueryWatchJsonContext : JsonSerializerContext
    {
    }
}
